name: Build and test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install check
      run: sudo apt-get install -y check
    - name: compile
      run: make
    - name: run unit tests
      run: make check
